services:
  - type: web
    name: ws-automation-bot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: ws-automation-bot
          property: host
